apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: f633b9okm-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-480e3cb9ef.3nsp.p3.openshiftapps.com/rhtap/rhtap-qe:cc71be84212eb4cea6c3011d6955cf19931f20be@sha256:9ae5755767edd068f48eb5dc3c3932747ad8a205d49a8550af05337cc7c8fea2
          name: container-image
